// AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
// Generated by training/generate_model_header.py on 2026-07-16 13:11:37
// Source: training/model_output/normalization_params.json and the
// quantized heatshield_model.tflite's input/output tensor metadata.
//
// These constants MUST match the trained model exactly. They are
// regenerated automatically every time you retrain + requantize, so the
// firmware's preprocessing can never silently drift out of sync with the
// model it is feeding.

#ifndef HEATSHIELD_MODEL_PARAMS_H
#define HEATSHIELD_MODEL_PARAMS_H

// Feature order (must match the order features are packed into the input
// tensor in preprocessing.cpp):
//   [0] Temperature
//   [1] Humidity
//   [2] HeartRate
//   [3] SpO2
//   [4] HeatIndex
#define HEATSHIELD_NUM_FEATURES 5
#define HEATSHIELD_NUM_CLASSES 4

// Per-feature standardization parameters: normalized = (raw - mean) / std
// Computed from the TRAINING split only (no validation/test leakage).
static const float HEATSHIELD_FEATURE_MEAN[HEATSHIELD_NUM_FEATURES] = {34.13552856f, 59.60208130f, 133.17324829f, 95.24756622f, 41.82123566f};
static const float HEATSHIELD_FEATURE_STD[HEATSHIELD_NUM_FEATURES]  = {6.52347565f, 18.12442589f, 31.87995720f, 2.68027949f, 12.40205383f};

// INT8 quantization parameters for the model's input tensor.
// int8_value = round(float_value / scale) + zero_point
static const float HEATSHIELD_INPUT_SCALE = 0.0201453418f;
static const int HEATSHIELD_INPUT_ZERO_POINT = 8;

// INT8 quantization parameters for the model's output tensor.
// float_value = (int8_value - zero_point) * scale
static const float HEATSHIELD_OUTPUT_SCALE = 0.0039062500f;
static const int HEATSHIELD_OUTPUT_ZERO_POINT = -128;

// Class names, indexed the same way as the model's output tensor.
static const char* const HEATSHIELD_CLASS_NAMES[HEATSHIELD_NUM_CLASSES] = {"SAFE", "WARNING", "DANGER", "CRITICAL"};

// Tensor arena size in bytes. See README.md "Tensor Arena Sizing".
#define HEATSHIELD_TENSOR_ARENA_SIZE 20480

#endif  // HEATSHIELD_MODEL_PARAMS_H
