"""
generate_model_header.py
=========================
Final step of the automated pipeline. Converts the quantized .tflite model
into a C byte array (model.h) and generates model_params.h containing the
normalization constants and quantization parameters needed by the ESP32
firmware -- then copies BOTH files directly into the firmware source tree.

This is what makes "no manual conversion" true: after running this script,
firmware/HeatShieldAI/src/model.h and model_params.h are ready to compile,
with values pulled straight from the actual trained/quantized model (not
hand-typed), so Python and firmware preprocessing can never drift apart.

Run: python generate_model_header.py
"""

import os
import datetime
import numpy as np
import tensorflow as tf

from common import (
    ROOT_DIR, MODEL_OUTPUT_DIR, FEATURE_NAMES, CLASS_NAMES, NUM_FEATURES,
    NUM_CLASSES, load_normalization_params, locate_firmware_dir,
)

TFLITE_PATH = os.path.join(MODEL_OUTPUT_DIR, "heatshield_model.tflite")
MODEL_H_OUT = os.path.join(MODEL_OUTPUT_DIR, "model.h")
FIRMWARE_SRC_DIR = os.path.join(locate_firmware_dir(), "src")
FIRMWARE_MODEL_H = os.path.join(FIRMWARE_SRC_DIR, "model.h")
FIRMWARE_MODEL_PARAMS_H = os.path.join(FIRMWARE_SRC_DIR, "model_params.h")

# Tensor arena size in bytes. See README.md "Tensor Arena Sizing" section
# for the full explanation of this number. Kept here (not hardcoded only in
# the .h template) so it's easy to find and tune.
TENSOR_ARENA_SIZE_BYTES = 20 * 1024  # 20 KB


def bytes_to_c_array(data: bytes, var_name: str) -> str:
    lines = [f"alignas(16) const unsigned char {var_name}[] = {{"]
    hex_bytes = [f"0x{b:02x}" for b in data]
    row_size = 12
    for i in range(0, len(hex_bytes), row_size):
        row = ", ".join(hex_bytes[i:i + row_size])
        lines.append(f"    {row},")
    lines.append("};")
    return "\n".join(lines)


def generate_model_h(tflite_bytes: bytes) -> str:
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    array_code = bytes_to_c_array(tflite_bytes, "g_heatshield_model")
    header = f"""// AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
// Generated by training/generate_model_header.py on {timestamp}
// Source: training/model_output/heatshield_model.tflite ({len(tflite_bytes)} bytes)
//
// Re-run the training pipeline and this script to regenerate this file
// after retraining. Any manual edits here will be overwritten.

#ifndef HEATSHIELD_MODEL_H
#define HEATSHIELD_MODEL_H

{array_code}

const unsigned int g_heatshield_model_len = {len(tflite_bytes)};

#endif  // HEATSHIELD_MODEL_H
"""
    return header


def format_float_array(values, precision=8):
    return ", ".join(f"{v:.{precision}f}f" for v in values)


def generate_model_params_h(mean, std, input_details, output_details) -> str:
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    in_scale, in_zero_point = input_details["quantization"]
    out_scale, out_zero_point = output_details["quantization"]

    feature_comment = "\n".join(
        f"//   [{i}] {name}" for i, name in enumerate(FEATURE_NAMES)
    )
    class_array = ", ".join(f"\"{c}\"" for c in CLASS_NAMES)

    header = f"""// AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
// Generated by training/generate_model_header.py on {timestamp}
// Source: training/model_output/normalization_params.json and the
// quantized heatshield_model.tflite's input/output tensor metadata.
//
// These constants MUST match the trained model exactly. They are
// regenerated automatically every time you retrain + requantize, so the
// firmware's preprocessing can never silently drift out of sync with the
// model it is feeding.

#ifndef HEATSHIELD_MODEL_PARAMS_H
#define HEATSHIELD_MODEL_PARAMS_H

// Feature order (must match the order features are packed into the input
// tensor in preprocessing.cpp):
{feature_comment}
#define HEATSHIELD_NUM_FEATURES {NUM_FEATURES}
#define HEATSHIELD_NUM_CLASSES {NUM_CLASSES}

// Per-feature standardization parameters: normalized = (raw - mean) / std
// Computed from the TRAINING split only (no validation/test leakage).
static const float HEATSHIELD_FEATURE_MEAN[HEATSHIELD_NUM_FEATURES] = {{{format_float_array(mean)}}};
static const float HEATSHIELD_FEATURE_STD[HEATSHIELD_NUM_FEATURES]  = {{{format_float_array(std)}}};

// INT8 quantization parameters for the model's input tensor.
// int8_value = round(float_value / scale) + zero_point
static const float HEATSHIELD_INPUT_SCALE = {in_scale:.10f}f;
static const int HEATSHIELD_INPUT_ZERO_POINT = {in_zero_point};

// INT8 quantization parameters for the model's output tensor.
// float_value = (int8_value - zero_point) * scale
static const float HEATSHIELD_OUTPUT_SCALE = {out_scale:.10f}f;
static const int HEATSHIELD_OUTPUT_ZERO_POINT = {out_zero_point};

// Class names, indexed the same way as the model's output tensor.
static const char* const HEATSHIELD_CLASS_NAMES[HEATSHIELD_NUM_CLASSES] = {{{class_array}}};

// Tensor arena size in bytes. See README.md "Tensor Arena Sizing".
#define HEATSHIELD_TENSOR_ARENA_SIZE {TENSOR_ARENA_SIZE_BYTES}

#endif  // HEATSHIELD_MODEL_PARAMS_H
"""
    return header


def main():
    print(f"Loading quantized model from {TFLITE_PATH}")
    with open(TFLITE_PATH, "rb") as f:
        tflite_bytes = f.read()

    interpreter = tf.lite.Interpreter(model_content=tflite_bytes)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]

    mean, std = load_normalization_params()

    model_h = generate_model_h(tflite_bytes)
    params_h = generate_model_params_h(mean, std, input_details, output_details)

    os.makedirs(MODEL_OUTPUT_DIR, exist_ok=True)
    os.makedirs(FIRMWARE_SRC_DIR, exist_ok=True)

    # Write to training/model_output/ (reference copy)
    with open(MODEL_H_OUT, "w") as f:
        f.write(model_h)
    print(f"Wrote {MODEL_H_OUT}")

    # Write directly into the firmware source tree (this IS the deployed copy)
    with open(FIRMWARE_MODEL_H, "w") as f:
        f.write(model_h)
    print(f"Wrote {FIRMWARE_MODEL_H}")

    with open(FIRMWARE_MODEL_PARAMS_H, "w") as f:
        f.write(params_h)
    print(f"Wrote {FIRMWARE_MODEL_PARAMS_H}")

    print(f"\nModel size: {len(tflite_bytes)} bytes ({len(tflite_bytes)/1024:.2f} KB)")
    print(f"Tensor arena configured: {TENSOR_ARENA_SIZE_BYTES} bytes ({TENSOR_ARENA_SIZE_BYTES/1024:.1f} KB)")
    print("\nDone. The firmware source tree now has an up-to-date model.h and model_params.h.")


if __name__ == "__main__":
    main()
